### ISSUE TITLE
Unable to install under Ubuntu 20.04 LTS 64-bit

### ISSUE THREAD

**Issue by brewmanz** [mireq/esp32-simulator#1]
I clone the repo and run install, but it fails. I have run the install several times (sometimes it helps); the last few have finished:
```
XXX:~/git/esp-idf$ ./install.sh
Installing ESP-IDF tools
Installing tools: xtensa-esp32-elf, xtensa-esp32s2-elf, esp32ulp-elf, esp32s2ulp-elf, openocd-esp32
Skipping xtensa-esp32-elf@esp-2020r2-8.2.0 (already installed)
Skipping xtensa-esp32s2-elf@esp-2020r2-8.2.0 (already installed)
Skipping esp32ulp-elf@2.28.51-esp-20191205 (already installed)
Skipping esp32s2ulp-elf@2.28.51-esp-20191205 (already installed)
Skipping openocd-esp32@v0.10.0-esp32-20200709 (already installed)
Installing Python environment and packages
Creating a new Python environment in /home/XXX/.espressif/python_env/idf4.3_py2.7_env
Installing virtualenv
/usr/bin/python: No module named pip
Traceback (most recent call last):
  File "/home/XXX/git/esp-idf/tools/idf_tools.py", line 1492, in <module>
    main(sys.argv[1:])
  File "/home/XXX/git/esp-idf/tools/idf_tools.py", line 1488, in main
    action_func(args)
  File "/home/XXX/git/esp-idf/tools/idf_tools.py", line 1205, in action_install_python_env
    stdout=sys.stdout, stderr=sys.stderr)
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python', '-m', 'pip', 'install', '--user', 'virtualenv']' returned non-zero exit status 1
```
It looks to me like the failure point is `/usr/bin/python: No module named pip`

PS I am using the 'Using Ubuntu' steps and the previous apt install step gives me
```
XXX:~/git/esp-idf$ sudo apt install git wget flex bison gperf python3 python3-pip python3-setuptools python3-serial python3-click python3-cryptography python3-future python3-pyparsing python3-pyelftools cmake ninja-build ccache libffi-dev libssl-dev libusb-1.0-0
[sudo] password for XXX: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
bison is already the newest version (2:3.5.1+dfsg-1).
ccache is already the newest version (3.7.7-1).
cmake is already the newest version (3.16.3-1ubuntu1).
flex is already the newest version (2.6.4-6.2).
git is already the newest version (1:2.25.1-1ubuntu3).
libffi-dev is already the newest version (3.3-4).
libssl-dev is already the newest version (1.1.1f-1ubuntu2).
libusb-1.0-0 is already the newest version (2:1.0.23-2build1).
python3 is already the newest version (3.8.2-0ubuntu2).
python3-click is already the newest version (7.0-3).
python3-cryptography is already the newest version (2.8-3).
python3-future is already the newest version (0.18.2-2).
python3-pyelftools is already the newest version (0.26-1ubuntu1).
python3-pyparsing is already the newest version (2.4.6-1).
python3-serial is already the newest version (3.4-5.1).
python3-setuptools is already the newest version (45.2.0-1).
wget is already the newest version (1.20.3-1ubuntu1).
gperf is already the newest version (3.1-1build1).
ninja-build is already the newest version (1.10.0-1build1).
python3-pip is already the newest version (20.0.2-5ubuntu1).
The following package was automatically installed and is no longer required:
  libfprint-2-tod1
Use 'sudo apt autoremove' to remove it.
0 to upgrade, 0 to newly install, 0 to remove and 0 not to upgrade.
```

**Comment by mireq** [comment]
Your ubuntu is misconfigured. It should use python 3, not python 2. Switch the default python to python 3.
